[package]
name = "train"
type = "contract"
authors = [""]
compiler_version = ">=0.25.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.4", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.4", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }