name: Starknet Tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'chains/starknet/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'chains/starknet/**'

jobs:
  run-starknet-tests:
    name: Run Starknet Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: chains/starknet/tests 
        run: |
          rm -f package-lock.json
          npm install
          npm install typescript ts-node @types/node starknet

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # - name: Install and Run Katana (Local Starknet Devnet)
      #   run: |
      #     curl -L https://foundry.paradigm.xyz | bash
      #     export PATH="$HOME/.foundry/bin:$PATH"
      #     foundryup
      #     katana --accounts 5 --disable-fee --host 127.0.0.1 --port 5050 > katana.log 2>&1 &
      #     sleep 15
      #     curl http://127.0.0.1:5050 || (cat katana.log && exit 1)
      #   shell: bash
      - name: Install Foundry and Katana
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          $HOME/.foundry/bin/foundryup
          $HOME/.foundry/bin/foundryup -C anvil --branch nightly
        
      - name: Run Katana
        run: |
          export PATH="$HOME/.foundry/bin:$PATH"
          katana --accounts 5 --disable-fee --host 127.0.0.1 --port 5050 > katana.log 2>&1 &
          sleep 15
          curl http://127.0.0.1:5050 || (cat katana.log && exit 1)

      - name: Compile Starknet Contracts
        working-directory: chains/starknet/tests
        run: |
          npm run build

      - name: Run Starknet Tests
        working-directory: chains/starknet/tests
        run: |
          npx ts-node starknet_tests.ts