name: Starknet Tests

on:
  push:
    branches: [ dev ]
    paths:
      - 'chains/starknet/**'
  pull_request:
    branches: [ dev ]
    paths:
      - 'chains/starknet/**'

jobs:
  run-starknet-tests:
    name: Run Starknet Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: chains/starknet/tests 
        run: |
          rm -f package-lock.json
          npm install
          npm install typescript ts-node @types/node starknet

      # - name: Setup Rust
      #   uses: dtolnay/rust-toolchain@stable

      - name: Install Starkli 
        working-directory: chains/starknet/tests 
        run: |
          curl https://get.starkli.sh | sh
          echo "$HOME/.starkli/bin" >> $GITHUB_PATH
          starkliup
          
      - name: Install Scarb
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://docs.swmansion.com/scarb/install.sh -s -- -v 2.9.4 | sh
          echo "$HOME/.scarb/bin" >> $GITHUB_PATH

      - name: Install Dojo (Katana)
        working-directory: chains/starknet/tests 
        run: |
          curl -L https://install.dojoengine.org | bash
          source "$HOME/.config/.dojo/env"
          dojoup 
          echo "$HOME/.config/.dojo/bin" >> $GITHUB_PATH

      - name: Run Katana
        working-directory: chains/starknet/tests 
        run: |
          export PATH="$HOME/.config/.dojo/bin:$PATH"
          RUNNER_TRACKING_ID="" katana --dev --dev.no-fee &
          sleep 15
          curl http://127.0.0.1:5050

      - name: Compile Starknet Contracts
        working-directory: chains/starknet/tests
        run: |
          npm run build

      - name: Run Starknet Tests
        working-directory: chains/starknet/tests
        run: |
          npx ts-node starknet_tests.ts